{% set name = "construct" %}
{% set version = "2.10.67" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 730235fedf4f2fee5cfadda1d14b83ef1bf23790fb1cc579073e10f70a050883

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - construct
    - construct.lib

about:
  home: http://construct.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A powerful declarative symmetric parser/builder for binary data

extra:
  recipe-maintainers:
    - DominicAntonacci
    - kevinheavey
