travis:
  secure:
    BINSTAR_TOKEN: s3nClSAKjGl9UlIygh19SWmPyAm1LNpi7DugdvcYycKFeuTqQl5J7MUbabPoPvaaepscEQjIEUjEEwY2I1T9OL5/MAkUHKoMpLGO8H6p1WAHl+uUhxBjKavN0L99Uek/MmWLVuts8hFiVMQ9tiqLTP0zPAlDPjMfvYYNpSqG+4T/Z6vqYkzPdL49Kz8xNvbvwelPKVPMurJ+CfZq2NgUfbVHlDym0OOSYGgZBZx6SuEbAxfkFugS+mEkUoXfNAas41qBbc+kC6bP7fUmlk4zRGs9fpEUzzGLfpth11MpVPkMJOHWPpXewnBdHTCcqDZxBE4R+Y1kyYxjFVNx4YGwINjh3fTdgijV7YGl7ul6X0zhRW7SUj/W/6RgYLr8QBMdUd0lSx5Y/cBrTiBOWEvktLdkxGN1WCc1ICTYH2vl870OYUuOPBG3w8+S5yzPgC5J+yB/63Sl52cYJ9kiMKpEOqeXBJK2U2p79Xg/iARCX3QOpcfzRxU7aNB+uigzTttvrL+GnQvWGDiXdfw6Wmo2YSrZaZrUKROfHfQ5i2LebFe0nd+iz4ORsB3o5KsH5DTdmMVQbALPIWo3dBhpGZbZWyxVcO8iO1FCAalzCO09P0SMR7DTPgZ+yL03XNLKQH8do3zlwfjhTnCR3x5mwJCexKf5UHOmYuD9+9BvZC0F3k8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
